### ISSUE TITLE
Support plain TCP (allow users to completely disable TLS)

### ISSUE THREAD

**Issue by jordansissel** [elastic/ruby-lumberjack#12]
A configuration option in the API should exist to choose to not run the lumberjack protocol over TLS. Disabling TLS would make the protocol work exactly the same except it's run over TCP (unencrypted).

**Comment by sandstrom** [comment]
@jordansissel  Thanks for this Jordan, much appreciated! :boat:

**Comment by ph** [comment]
@sandstrom I have created this https://github.com/logstash-plugins/logstash-input-lumberjack/issues/55 to add the option, keep in mind that this option will only be available with filebeat https://github.com/elastic/filebeat which will be the `logstash-forwarder` replacement.

**Comment by sandstrom** [comment]
@ph Great, thanks!
