### ISSUE TITLE
ssl_certificate never used in Client

### ISSUE THREAD

**Issue by lazyfrosch** [elastic/ruby-lumberjack#4]
Prove me wrong, but I think the `ssl_certificate` is never used in client.

So the connection to a server doesn't get validated?

**Comment by ph** [comment]
I've been looking through the code and **yes** this settings seem to be not used but required.

**Comment by ph** [comment]
thanks to @jsvd's archeology skills it used to be there https://github.com/elastic/ruby-lumberjack/blob/ea49476be4c8fb3893b9f1e67b34e6277c44df24/lib/lumberjack/client.rb#L77

**Comment by lazyfrosch** [comment]
But even the verification is disable there :cry:

**Comment by ph** [comment]
@lazyfrosch I'll fix it :( I am messing with another SSL problem so I'll do it at the same time.

**Comment by lazyfrosch** [comment]
@ph thanks for that :smile:
